In [1]:
import numpy as np

In [2]:
a = np.array([6,7,8,9])

In [3]:
a[0:2]

array([6, 7])

In [4]:
a[2:]

array([8, 9])

In [5]:
a[-1]

np.int64(9)

In [6]:
a[-2:]

array([8, 9])

In [7]:
b = np.array([[1,2,3],
              [4,5,6,],
              [7,8,9,]])

In [12]:
# to write 6 
b[1,2]

np.int64(6)

In [13]:
b[2,0]

np.int64(7)

In [14]:
b[-1]

array([7, 8, 9])

In [15]:
b[-1, 0:2]

array([7, 8])

In [27]:
b[:,2:3]

array([[3],
       [6],
       [9]])

In [33]:
# stack
c = np.array([[101,'ayush'],[102,'subho'],[103,'ayushman']])
d = np.array([[101,'25th jan'],[102,'25jan'],[103,'23jan']])


In [ ]:
# horizontal stack
f = np.hstack((c,d))
f

array([['101', 'ayush', '101', '25th jan'],
       ['102', 'subho', '102', '25jan'],
       ['103', 'ayushman', '103', '23jan']], dtype='<U21')

In [40]:
# vertical stack
e = np.array([[101,'ayush'],[102,'subho'],[103,'ayushman']])
g = np.vstack((c,e))
g


array([['101', 'ayush'],
       ['102', 'subho'],
       ['103', 'ayushman'],
       ['101', 'ayush'],
       ['102', 'subho'],
       ['103', 'ayushman']], dtype='<U21')

In [44]:
# split - horizontal and vertical
np.hsplit(g,[1])

[array([['101'],
        ['102'],
        ['103'],
        ['101'],
        ['102'],
        ['103']], dtype='<U21'),
 array([['ayush'],
        ['subho'],
        ['ayushman'],
        ['ayush'],
        ['subho'],
        ['ayushman']], dtype='<U21')]

In [47]:
g1 , g2 =np.vsplit(g,[3])

In [48]:
g1

array([['101', 'ayush'],
       ['102', 'subho'],
       ['103', 'ayushman']], dtype='<U21')

In [49]:
g2

array([['101', 'ayush'],
       ['102', 'subho'],
       ['103', 'ayushman']], dtype='<U21')