In [96]:
import numpy as np

In [97]:
a = np.array([6,7,8,9])

In [98]:
a[0:2]

array([6, 7])

In [99]:
a[2:]

array([8, 9])

In [100]:
a[-1]

np.int64(9)

In [101]:
a[-2:]

array([8, 9])

In [102]:
b = np.array([[1,2,3],
              [4,5,6,],
              [7,8,9,]])

In [103]:
# to write 6 
b[1,2]

np.int64(6)

In [104]:
b[2,0]

np.int64(7)

In [105]:
b[-1]

array([7, 8, 9])

In [106]:
b[-1, 0:2]

array([7, 8])

In [107]:
b[:,2:3]

array([[3],
       [6],
       [9]])

In [112]:
# stack
c = np.array([[101,'ayush',230],[102,'subho',234],[103,'ayushman',530]])
d = np.array([[101,'25th jan'],[102,'25jan'],[103,'23jan']])


In [113]:
# horizontal stack
f = np.hstack((c,d))
f

array([['101', 'ayush', '230', '101', '25th jan'],
       ['102', 'subho', '234', '102', '25jan'],
       ['103', 'ayushman', '530', '103', '23jan']], dtype='<U21')

In [118]:
# vertical stack
e = np.array([[101,'ayush',230],[102,'subho',234],[103,'ayushman',530]])
g = np.vstack((c,e))
g


array([['101', 'ayush', '230'],
       ['102', 'subho', '234'],
       ['103', 'ayushman', '530'],
       ['101', 'ayush', '230'],
       ['102', 'subho', '234'],
       ['103', 'ayushman', '530']], dtype='<U21')

In [119]:
# split - horizontal and vertical
np.hsplit(g,[1])

[array([['101'],
        ['102'],
        ['103'],
        ['101'],
        ['102'],
        ['103']], dtype='<U21'),
 array([['ayush', '230'],
        ['subho', '234'],
        ['ayushman', '530'],
        ['ayush', '230'],
        ['subho', '234'],
        ['ayushman', '530']], dtype='<U21')]

In [120]:
g1 , g2 =np.vsplit(g,[3])

In [121]:
g1

array([['101', 'ayush', '230'],
       ['102', 'subho', '234'],
       ['103', 'ayushman', '530']], dtype='<U21')

In [122]:
g2

array([['101', 'ayush', '230'],
       ['102', 'subho', '234'],
       ['103', 'ayushman', '530']], dtype='<U21')

In [123]:
monthly_sales= np.array([34,35,36,31,32,24])
result = monthly_sales< 32
result

array([False, False, False,  True, False,  True])

In [124]:
monthly_sales[result]

array([31, 24])

In [125]:
index_max_value =np.argmax(monthly_sales)
index_max_value

np.int64(2)

In [126]:
# max value 
monthly_sales[2]

np.int64(36)

In [135]:
f

array([['101', 'ayush', '230', '101', '25th jan'],
       ['102', 'subho', '234', '102', '25jan'],
       ['103', 'ayushman', '530', '103', '23jan']], dtype='<U21')

In [136]:
f[:,2]

array(['230', '234', '530'], dtype='<U21')

In [137]:
f_index= np.argmax(f[:,2].astype(float))

In [138]:
f[f_index]

array(['103', 'ayushman', '530', '103', '23jan'], dtype='<U21')