In [12]:
print("hello world")

hello world


In [13]:
import numpy as np

In [14]:
"array" in dir(np)

True

In [15]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
type(arr)

numpy.ndarray

In [ ]:
python_array=np.array(range(100))
python_array[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
python_array.nbytes

800

In [27]:
python_list=list(range(100))
python_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2800

In [30]:
l1 = [1,2,3]
l2 =[4,5,6]
tuple(zip(l1,l2))

((1, 4), (2, 5), (3, 6))

In [32]:
l3 = l1 + l2
l3

[1, 2, 3, 4, 5, 6]

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = arr1 + arr2
arr3

array([5, 7, 9])