In [12]:
print("hello world")

hello world


In [13]:
import numpy as np

In [14]:
"array" in dir(np)

True

In [15]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

dtype('int64')

array took less memoery and it's faster than list

In [ ]:
python_array=np.array(range(100))
python_array[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
python_array.nbytes

800

In [27]:
python_list=list(range(100))
python_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2800

zip function

In [30]:
l1 = [1,2,3]
l2 =[4,5,6]
tuple(zip(l1,l2))

((1, 4), (2, 5), (3, 6))

In [32]:
l3 = l1 + l2
l3

[1, 2, 3, 4, 5, 6]

we can do vector operation in array

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = arr1 + arr2
arr3

array([5, 7, 9])

***Operation of array***

In [40]:
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
c_unsigned32 = a - b
c_unsigned32

array([-3, -3, -3])

array creation

In [43]:
revenu_q1=np.array([10,20,30])
revenu_q1

array([10, 20, 30])

how to check demmention

In [44]:
revenu_q1.ndim

1

In [45]:
rev = np.array([[10,20,30],[30,40,50]])
rev.ndim

2

In [46]:
rev

array([[10, 20, 30],
       [30, 40, 50]])

In [47]:
rev[1,2]

np.int64(50)

In [48]:
rev.dtype


dtype('int64')

while creating the array i can give data type


In [ ]:
rev2 = np.array([[10,20,30],[30,40,50]],dtype=np.float32)  # we can give data types manually to fix size
rev2.dtype

dtype('float32')

In [ ]:
rev2.itemsize  #eact item size

4

In [ ]:
rev2.size   # no of elements

6

In [53]:
rev2.shape

(2, 3)

In [54]:
rev

array([[10, 20, 30],
       [30, 40, 50]])

In [ ]:
np.sort(rev)

array([[10, 20, 30],
       [30, 40, 50]])

In [ ]:
np.sort(rev,axis=None)

array([10, 20, 30, 30, 40, 50])

In [59]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [66]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [67]:
rev

array([[10, 20, 30],
       [30, 40, 50]])

In [68]:
rev.ravel()

array([10, 20, 30, 30, 40, 50])

In [69]:
rev.flatten()

array([10, 20, 30, 30, 40, 50])

In [71]:
rev.reshape(6,1)

array([[10],
       [20],
       [30],
       [30],
       [40],
       [50]])

In [72]:
rev.min()

np.int64(10)

In [74]:
rev2.max()

np.float32(50.0)

In [ ]:
rev.sum(axis=0)  # parameter axis canbe None , 1 , 0 ... it will sum according to that

array([40, 60, 80])

In [78]:
rev

array([[10, 20, 30],
       [30, 40, 50]])

In [80]:
for row in rev:
    print ("row->",row)

row-> [10 20 30]
row-> [30 40 50]


In [81]:
d = np.array([23,34,65])


In [82]:
np.sqrt(d)

array([4.79583152, 5.83095189, 8.06225775])

In [83]:
np.square(d)

array([ 529, 1156, 4225])

In [ ]:
np.std(d)  # standerd daviation

np.float64(17.78263822446552)