Matrix method using numpy

In [2]:
import numpy as np

In [ ]:

matrix_quater1 =np.array([[200,220,250],    #product1
                          [150,180,210],    #product2
                          [300,330,360]    #product3
                          ])
matrix_quater1   # sells of quater 1    

array([[200, 220, 250],
       [150, 180, 210],
       [300, 330, 360]])

In [ ]:
matrix_quater2 =np.array([[209,231,259],  #product1
                          [155,192,222],  #product2
                          [310,340,375]  #product3
                          ])
matrix_quater2 #sells of quater 2

array([[209, 231, 259],
       [155, 192, 222],
       [310, 340, 375]])

In [17]:
#total sells of both quater 
total =(matrix_quater1+matrix_quater2)
total

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [18]:
#improvmnt in q2
matrix_quater2-matrix_quater1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [ ]:
#percentage of sells increase
(matrix_quater2-matrix_quater1)*100/matrix_quater1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [25]:
prices = np.array([
    [200,300,402],
    [300,212,453],
    [234,324,53]
])
q1_revenue = matrix_quater1*prices
q2_revenue = matrix_quater2*prices


In [26]:
q1_revenue

array([[ 40000,  66000, 100500],
       [ 45000,  38160,  95130],
       [ 70200, 106920,  19080]])

In [27]:
q2_revenue

array([[ 41800,  69300, 104118],
       [ 46500,  40704, 100566],
       [ 72540, 110160,  19875]])

In [35]:
#discount 
dis_q1 = q1_revenue*0.2
dis_q2 = q2_revenue*0.2
dis_q1,dis_q2

(array([[ 8000., 13200., 20100.],
        [ 9000.,  7632., 19026.],
        [14040., 21384.,  3816.]]),
 array([[ 8360. , 13860. , 20823.6],
        [ 9300. ,  8140.8, 20113.2],
        [14508. , 22032. ,  3975. ]]))

In [ ]:
#net revenue = revenue - discount for both quater
net_revenue_q1 = q1_revenue - dis_q1
net_revenue_q2 = q2_revenue - dis_q2
net_revenue_q1,net_revenue_q2

(array([[32000., 52800., 80400.],
        [36000., 30528., 76104.],
        [56160., 85536., 15264.]]),
 array([[33440. , 55440. , 83294.4],
        [37200. , 32563.2, 80452.8],
        [58032. , 88128. , 15900. ]]))

In [ ]:
#total net revenue
tnr=np.sum(net_revenue_q1)

np.float64(464792.0)

In [40]:
features = np.array([
    [200,3],     #house 1
    [1000,2]     #house 2
])
weights = np.array([150,50000])
weights

array([  150, 50000])